spring.application.name: plic

---

dashboard.url: http://127.0.0.1

---

spring.jpa:
  database: MYSQL
  showSql: true
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  properties.hibernate.hbm2ddl.auto: update
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true
---

spring.datasource:
  platform: h2
  url: jdbc:h2:mem:plic;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
  username: sa
  initialize: true
---
spring.h2.console:
  enabled: true
  path : /h2-console
  settings.web-allow-others: true
---

spring.profiles: local-test

