INSERT INTO TICKET(USER_ID, PERFORMENCE_ID,FACILITY_NAME,PERFORMENCE_NAME) VALUES (1, '1234', 'CJ아지트 대학로', '마이버킷리스트');
INSERT INTO WISHLIST(USER_ID, FACILITY_NAME, PERFORMANCE_NAME, PERFORMANCE_START_DATE, PERFORMANCE_END_DATE) values (1, 'CJ아지트 대학로', '마이버킷리스트', '2018/06/01', '2018/06/30');
